# -*- coding: utf-8 -*-
"""DNN1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oQLpXBWskEMsW-xVYUyxw05L9O0d1NMd

## ===============================================
## 🧠 Airline Delay Cause Classification with Keras
## Author: [Your Name]
## Date: [Month, Year]
## Description:
## This notebook builds and evaluates a neural network
## to classify whether weather delays are significant
## (over 100 minutes) using airline delay data.
## ===============================================
"""

# Commented out IPython magic to ensure Python compatibility.
# --- Importing Essential Libraries ---
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import numpy as np

# --- Load Dataset ---
data = pd.read_csv('/content/Airline_Delay_Cause.csv')
data.head()

# --- Basic Dataset Info ---
data.info()

# --- Drop Unnecessary Columns ---
# Removing columns that are non-numeric or identifiers
data = data.drop(['carrier', 'carrier_name', 'airport', 'airport_name'], axis=1)

# --- Drop Missing Values ---
data.dropna(inplace=True)
data.info()

# --- Explore Range of Weather Delay ---
print(data['weather_delay'].min(), data['weather_delay'].max())

# --- Create Binary Target Variable ---
# 1 → weather delay > 100 minutes (significant delay)
# 0 → otherwise
data['WDCase'] = data['weather_delay'].apply(lambda x: 1 if x > 100 else 0)

# --- Check Class Distribution ---
data['WDCase'].value_counts()

# --- Separate Features and Target ---
X = data.drop(['WDCase'], axis=1)
y = data['WDCase']

# --- Split Data into Train/Test Sets ---
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=44, shuffle =True)

print('X_train shape is ' , X_train.shape)
print('X_test shape is ' , X_test.shape)
print('y_train shape is ' , y_train.shape)
print('y_test shape is ' , y_test.shape)

# --- Build Keras Sequential Model ---
import tensorflow as tf
import keras

KerasModel = keras.models.Sequential([
    keras.layers.Dense(8, activation='tanh'),
    keras.layers.Dense(128, activation='sigmoid'),
    keras.layers.Dense(64, activation='tanh'),
    keras.layers.Dense(32, activation='tanh'),
    keras.layers.Dense(1, activation='sigmoid')  # Output layer for binary classification
])

# --- Define Optimizer (Adam with weight decay) ---
Opt = tf.keras.optimizers.Adam(
    learning_rate=0.001,
    weight_decay=0.004,
    beta_1=0.9,
    beta_2=0.999,
    epsilon=1e-07,
    amsgrad=False,
    name="Adam"
)

# --- Compile Model ---
KerasModel.compile(optimizer =Opt,loss='binary_crossentropy',metrics=['accuracy'])

# --- Train the Model with Early Stopping ---
history = KerasModel.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=10000,
    verbose=1,
    callbacks=[tf.keras.callbacks.EarlyStopping(
        patience=10,
        monitor='val_accuracy',
        restore_best_weights=True
    )]
)

# --- Display Model Summary ---
print(KerasModel.summary())

# --- Save and Reload Model ---
KerasModel.save('KerasModel.h5')
NewKerasModel = keras.models.load_model('KerasModel.h5')

# --- Model Predictions ---
y_pred = NewKerasModel.predict(X_test)
print(f'Prediction Shape: {y_pred.shape}')

# --- Evaluate Model on Test Data ---
ModelLoss, ModelAccuracy = NewKerasModel.evaluate(X_test, y_test)
print(f'Model Loss: {(ModelLoss)*100:.2f}')
print(f'Model Accuracy: {(ModelAccuracy)*100:.2f}')

# --- Plot Accuracy over Epochs ---
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy Over Epochs')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

# --- Plot Loss over Epochs ---
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model Loss Over Epochs')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

# --- Convert Predicted Probabilities to Binary Labels ---
y_pred = [np.round(i[0]) for i in y_pred]

# --- Confusion Matrix Visualization ---
from sklearn.metrics import confusion_matrix
import seaborn as sns

CM = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
sns.heatmap(CM, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.title('Confusion Matrix', fontsize=14)
plt.xlabel('Predicted Labels', fontsize=12)
plt.ylabel('True Labels', fontsize=12)
plt.show()

# --- Classification Report ---
from sklearn.metrics import classification_report
ClassificationReport = classification_report(y_test, y_pred)
print('Classification Report:\n', ClassificationReport)